name: Purge Artifacts

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  purge:
    name: "Supprimer les anciens artifacts"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: write
    steps:
      - name: "Purger les artifacts de plus de 30 jours"
        uses: c-hive/gha-remove-artifacts@ca9712b
        with:
          age: '1 month'
          skip-tags: true
          skip-recent: 2